import { BrandLogo } from "@/components/brand-logo";
import Link from "next/link";
import { LandingCalculator } from "@/components/landing-calculator";
import { LandingPricing } from "@/components/landing-pricing";
import { landingConfig, landingFeatures, landingStats, statsNote, landingFaq } from "@/lib/landing-config";
import { BUSINESS_TYPES } from "@/lib/business-types";
import { Icon } from "@/components/icons";

const button = "landing-solid-link inline-flex min-h-12 items-center justify-center rounded-full bg-[#0B806C] px-7 text-sm font-bold text-white transition-transform hover:-translate-y-1";
const outline = "landing-outline-link inline-flex min-h-12 items-center justify-center rounded-full border-2 border-white px-7 text-sm font-bold transition-colors hover:bg-white hover:text-[#102D46]";
function Eyebrow({children}:{children:React.ReactNode}){return <span className="landing-eyebrow">{children}</span>}
function Heading({eyebrow,children,description}:{eyebrow:string;children:React.ReactNode;description:string}){return <div className="mb-10 max-w-4xl sm:mb-14"><Eyebrow>{eyebrow}</Eyebrow><h2 className="landing-title mt-5">{children}</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-black/65 sm:text-lg">{description}</p></div>}
function Preview(){return <div className="relative mx-auto h-[430px] max-w-[520px] sm:h-[510px]">
  <div className="absolute left-[3%] top-[8%] h-[350px] w-[350px] rounded-full border border-white/40 sm:h-[445px] sm:w-[445px]"/>
  <div className="landing-float-slow absolute left-[1%] top-[8%] z-20 w-[76%] rotate-[-8deg] rounded-[1.5rem] border-2 border-[#102D46] bg-[#F7FAFC] p-6 shadow-[11px_13px_0_#102D46]">
    <div className="flex items-center justify-between text-[10px] font-extrabold uppercase tracking-widest text-black/55"><span>Programme partenaire</span><span className="text-xl text-[#109B81]">✳</span></div><div className="mt-7 font-display text-4xl uppercase leading-none">MAISON<br/>RIVOLI</div><p className="mt-2 text-xs text-black/55">Votre fidélité, simplement.</p>
    <div className="mt-7 grid grid-cols-4 gap-2">{Array.from({length:8},(_,i)=><div key={i} className={`grid aspect-square place-items-center rounded-full border-2 text-xs font-bold ${i<5?"border-[#102D46] bg-[#109B81] text-[#102D46]":"border-dashed border-black/25 text-black/25"}`}>{i<5?"✳":i+1}</div>)}</div><div className="mt-6 border-t border-black/15 pt-4 text-xs font-extrabold uppercase">50 / 80 points</div>
  </div>
  <div className="landing-float-fast absolute bottom-[8%] right-[1%] z-30 w-[64%] rotate-[6deg] rounded-[1.4rem] border-2 border-[#102D46] bg-white p-5 shadow-[9px_10px_0_#102D46]"><div className="flex items-center justify-between"><span className="text-[10px] font-extrabold uppercase tracking-widest text-black/50">Espace professionnel</span><span className="rounded-full bg-[#E4F3EF] px-2 py-1 text-[9px] font-bold text-[#0B806C]">● Actif</span></div><strong className="mt-4 block font-display text-5xl">24</strong><p className="text-xs text-black/55">passages suivis · aperçu de démonstration</p><div className="mt-5 flex h-14 items-end gap-2 border-b border-black/15 pb-1">{[30,55,38,68,48,82,60,92].map((h,i)=><span key={i} className="flex-1 rounded-t bg-[#109B81]" style={{height:`${h}%`}}/>)}</div></div>
  <div className="landing-float-fast absolute right-[1%] top-[1%] z-40 rotate-[7deg] rounded-full border-2 border-[#102D46] bg-[#C9EDE5] px-4 py-2 text-xs font-extrabold shadow-[4px_4px_0_#102D46]">NFC + QR ✦</div>
</div>}
export default function Home(){return <div className="landing-page overflow-hidden bg-[#F7FAFC] text-[#102D46]">
<section id="accueil" className="valorya-hero relative bg-[#102D46] text-white"><div className="landing-dots pointer-events-none absolute inset-0 opacity-30"/><nav className="landing-container relative z-50 flex min-h-[78px] items-center justify-between gap-4 border-b border-white/25"><Link href="#accueil" className="valorya-wordmark" aria-label="Valorya, accueil"><BrandLogo size={38} inverse /><span>Valorya</span></Link><div className="hidden items-center lg:flex">{[["Solution","solution"],["Métiers","secteurs"],["Fonctionnalités","fonctionnalites"],["Tarifs","tarifs"],["Questions","faq"]].map(([l,id])=><a key={id} href={`#${id}`} className="rounded-full px-5 py-3 text-sm font-bold hover:bg-white/15">{l}</a>)}</div><div className="flex items-center gap-2"><Link href="/business/login" className="hidden rounded-full px-4 py-2 text-sm font-bold sm:inline-flex">Connexion</Link><Link href="/business/login" className="landing-nav-cta rounded-full bg-white px-4 py-2.5 text-xs font-extrabold text-[#102D46] sm:px-6 sm:text-sm">Créer mon espace ↗</Link></div></nav>
<div className="landing-container relative grid min-h-[670px] items-center gap-8 py-12 lg:grid-cols-[1.05fr_.95fr]"><div className="order-2 lg:order-1"><Preview/></div><div className="order-1 max-w-2xl lg:order-2"><span className="inline-flex rounded-full border border-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[.15em]">Fidélité digitale pour PME</span><h1 className="mt-7 font-display text-[clamp(3.6rem,7.5vw,8rem)] uppercase leading-[.91] tracking-tight">VOTRE MARQUE.<br/><span className="text-[#109B81]">LEUR RÉFLEXE.</span></h1><p className="mt-7 max-w-xl text-base leading-relaxed text-white/95 sm:text-lg">Valorya aide restaurants, boutiques, salons et commerces de proximité à créer leur propre programme de fidélité : support NFC + QR, espace client, points, récompenses et pilotage professionnel.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/business/login" className={button}>Créer mon programme ↗</Link><Link href="/demo" className={outline}>Voir la démo</Link></div><p className="mt-7 text-xs font-medium text-white/80">Pas d’application à imposer à vos clients. Votre programme reste à votre image.</p></div></div>
<div className="relative border-t border-white/25 py-3"><div className="landing-container flex flex-wrap justify-center gap-x-10 gap-y-2 text-xs font-bold uppercase tracking-[.16em] text-white/90 sm:justify-between"><span>NFC + QR</span><span>Points & récompenses</span><span>Espace professionnel</span><span>Multi-commerce</span></div></div></section>
<section className="stats-band"><div className="landing-container"><div className="stats-grid">{landingStats.map(x=><div className="stat-card" key={x.value}><strong>{x.value}</strong><p>{x.text}</p></div>)}</div><p className="stats-note">{statsNote}</p></div></section>
<section id="solution" className="landing-section"><div className="landing-container"><Heading eyebrow="01 / LE PROBLÈME" description="La fidélité ne devrait pas dépendre d’une carte papier oubliée ni d’un logiciel compliqué. Valorya relie le comptoir, le téléphone du client et votre suivi professionnel.">GARDEZ LE LIEN<br/><span className="text-[#109B81]">APRÈS L’ACHAT.</span></Heading><div className="grid gap-5 md:grid-cols-2"><article className="rounded-[1.5rem] border-2 border-[#102D46] bg-white p-8"><span className="rounded-full bg-[#eee] px-4 py-2 text-xs font-extrabold uppercase">Sans programme structuré</span><h3 className="mt-8 font-display text-3xl uppercase">Vous servez. Puis vous perdez le fil.</h3><ul className="mt-7 space-y-5 text-sm leading-relaxed sm:text-base">{["Difficile de savoir qui revient et à quel rythme.","Les avantages sont peu visibles pour le client.","La fidélisation repose sur la mémoire de l’équipe."].map(x=><li key={x} className="flex gap-4"><b className="text-[#109B81]">×</b>{x}</li>)}</ul></article><article className="rounded-[1.5rem] border-2 border-[#102D46] bg-[#E4F3EF] p-8"><span className="rounded-full bg-[#102D46] px-4 py-2 text-xs font-extrabold uppercase text-white">Avec Valorya</span><h3 className="mt-8 font-display text-3xl uppercase">Chaque passage enrichit la relation.</h3><ul className="mt-7 space-y-5 text-sm leading-relaxed sm:text-base">{["Le client rejoint votre programme en quelques gestes.","Son solde et ses récompenses restent accessibles sur mobile.","Vous pilotez points, visites et avantages depuis votre espace."].map(x=><li key={x} className="flex gap-4"><b className="text-[#0B806C]">✓</b>{x}</li>)}</ul></article></div></div></section>
<section id="materiel" className="landing-section bg-[#102D46] text-white"><div className="landing-container grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><Eyebrow>02 / LE POINT DE CONTACT</Eyebrow><h2 className="mt-5 font-display text-[clamp(3rem,6vw,6rem)] uppercase leading-[.95]">POSEZ VALORYA.<br/><span className="text-[#109B81]">LA CONVERSATION COMMENCE.</span></h2><p className="mt-6 max-w-xl text-base leading-relaxed text-white/65">Une carte ou plaque Valorya peut réunir NFC et QR code. Le client approche son téléphone, rejoint le programme de votre établissement et retrouve ensuite son espace fidélité.</p></div><div className="grid gap-4 sm:grid-cols-3">{[["01","Approcher","NFC ou QR au comptoir"],["02","Rejoindre","Formulaire court et identifié au commerce"],["03","Revenir","Points, avantages et récompenses visibles"]].map(([n,t,d])=><article key={n} className="rounded-[1.5rem] border border-white/20 bg-white/5 p-6"><strong className="font-display text-5xl text-[#109B81]">{n}</strong><h3 className="mt-8 font-display text-2xl uppercase">{t}</h3><p className="mt-3 text-sm leading-relaxed text-white/60">{d}</p></article>)}</div></div></section>
<section id="secteurs" className="landing-section bg-white"><div className="landing-container"><Heading eyebrow="03 / POUR VOTRE MÉTIER" description="Valorya s’adapte à votre activité : vocabulaire, récompenses suggérées et espace équipe se configurent en un clic à la création de votre compte.">UN ESPACE<br/><span className="text-[#109B81]">À VOTRE IMAGE.</span></Heading><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{BUSINESS_TYPES.filter(t=>t.key!=="autre").map(t=><article key={t.key} className="rounded-[1.4rem] border-2 border-[#102D46] bg-[#F7FAFC] p-6"><span className="grid size-12 place-items-center rounded-2xl bg-white text-[#109B81]"><Icon name={t.icon} size={26}/></span><h3 className="mt-6 font-display text-xl">{t.short}</h3><p className="mt-2 text-sm leading-relaxed text-black/65">{t.pitch}</p><p className="mt-4 text-xs font-bold uppercase tracking-wider text-black/45">Exemples de récompenses</p><ul className="mt-2 space-y-1 text-sm">{t.rewards.slice(0,2).map(r=><li key={r.name} className="flex gap-2"><b className="text-[#109B81]">✓</b>{r.name}</li>)}</ul></article>)}</div><p className="mt-8 text-center text-sm text-black/55">Un autre métier ? Choisissez « Autre » et personnalisez vos récompenses librement.</p></div></section>
<section id="fonctionnalites" className="landing-section"><div className="landing-container"><Heading eyebrow="04 / LA PLATEFORME" description="Valorya est conçu comme un outil B2B : le professionnel configure son programme, son équipe l’utilise et le client profite d’une expérience simple.">VOTRE PROGRAMME.<br/><span className="text-[#109B81]">VOS RÈGLES.</span></Heading><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{landingFeatures.map((f,i)=><article key={f.title} className="rounded-[1.4rem] border-2 border-[#102D46] bg-white p-7"><div className="flex justify-between"><span className="grid size-14 place-items-center rounded-2xl bg-[#EDF7F4] text-3xl text-[#109B81]">{f.icon}</span><span className="text-xs font-bold text-black/35">0{i+1}</span></div><h3 className="mt-9 font-display text-2xl uppercase">{f.title}</h3><p className="mt-3 text-sm leading-relaxed text-black/60">{f.description}</p></article>)}</div></div></section>
<section id="etapes" className="landing-section bg-[#E4F3EF]"><div className="landing-container"><Heading eyebrow="05 / MISE EN PLACE" description="Le parcours commercial est pensé pour une PME : une configuration courte, un support en point de vente et un outil que l’équipe peut comprendre rapidement.">DE L’IDÉE AU COMPTOIR<br/><span className="text-[#109B81]">EN 3 TEMPS.</span></Heading><div className="grid gap-5 md:grid-cols-3">{[["01","Configurez","Créez votre espace professionnel, votre établissement, vos points et vos récompenses."],["02","Déployez","Placez votre support Valorya NFC + QR là où vos clients le voient naturellement."],["03","Pilotez","Suivez l’activité et ajustez votre programme depuis le tableau de bord."]].map(([n,t,d])=><article key={n} className="rounded-[1.5rem] border-2 border-[#102D46] bg-[#F7FAFC] p-8"><span className="font-display text-6xl text-[#109B81]">{n}</span><h3 className="mt-8 font-display text-3xl uppercase">{t}</h3><p className="mt-3 text-sm leading-relaxed text-black/65">{d}</p></article>)}</div></div></section>
<section id="calculateur" className="landing-section bg-[#EDF7F4]"><div className="landing-container"><Heading eyebrow="06 / VOTRE SCÉNARIO" description="Testez une hypothèse à partir de votre fréquentation et de votre panier moyen. Le calcul est volontairement transparent et ne garantit aucun résultat.">METTEZ VOS CHIFFRES<br/><span className="text-[#109B81]">SUR LA TABLE.</span></Heading><LandingCalculator/></div></section>
<section id="confiance" className="landing-section"><div className="landing-container"><Heading eyebrow="07 / POUR LES PROS" description="Une solution de fidélité doit rester exploitable au quotidien et séparer correctement les établissements.">CONÇU POUR VOTRE<br/><span className="text-[#109B81]">ACTIVITÉ.</span></Heading><div className="grid gap-6 md:grid-cols-3">{landingConfig.trust.map(t=><article key={t.title} className="rounded-[1.5rem] border-2 border-[#102D46] bg-white p-7"><span className="text-3xl">{t.icon}</span><h3 className="mt-4 font-display text-xl">{t.title}</h3><p className="mt-2 text-sm leading-relaxed text-black/65">{t.description}</p></article>)}</div><ul className="mx-auto mt-10 grid max-w-4xl gap-3 sm:grid-cols-2">{landingConfig.differentiators.map(d=><li key={d} className="flex gap-3 rounded-2xl bg-[#E4F3EF] p-4 text-sm font-medium"><b className="text-[#109B81]">✓</b>{d}</li>)}</ul></div></section>
<section id="tarifs" className="landing-section bg-[#EDF7F4]"><div className="landing-container"><LandingPricing/></div></section>
<section id="faq" className="landing-section bg-white"><div className="landing-container max-w-3xl"><Heading eyebrow="08 / QUESTIONS" description="Les réponses aux questions que se posent le plus souvent les commerçants.">VOUS VOUS<br/><span className="text-[#109B81]">DEMANDEZ…</span></Heading><div className="space-y-3">{landingFaq.map(f=><details key={f.q} className="group rounded-2xl border-2 border-[#102D46] bg-[#F7FAFC] p-5"><summary className="cursor-pointer list-none font-bold">{f.q}<span className="float-right text-[#109B81] group-open:rotate-45">+</span></summary><p className="mt-3 text-sm leading-relaxed text-black/70">{f.a}</p></details>)}</div></div></section>
<section className="valorya-cta bg-[#102D46] py-20 text-white sm:py-28"><div className="landing-container"><Eyebrow>VALORYA POUR VOTRE PME</Eyebrow><h2 className="mt-5 font-display text-[clamp(3.5rem,8vw,8rem)] uppercase leading-[.94]">CRÉEZ UNE FIDÉLITÉ<br/>QUI PORTE<br/><span className="text-[#109B81]">VOTRE NOM.</span></h2><p className="mt-7 max-w-xl text-base leading-relaxed text-white/90">Testez le parcours professionnel, configurez un programme et montrez à vos clients une expérience de fidélité cohérente avec votre marque.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/business/login" className={button}>Créer mon espace ↗</Link><Link href="/demo" className={outline}>Explorer la démo</Link></div></div></section>
<footer className="bg-[#102D46] py-9 text-white"><div className="landing-container flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><span className="valorya-wordmark"><BrandLogo size={36} inverse /><span>Valorya</span></span><p className="mt-1 text-xs text-white/50">La fidélité digitale pensée pour les PME.</p></div><div className="flex flex-wrap gap-5 text-xs font-semibold"><Link href="/privacy">Confidentialité</Link><Link href="/terms">Conditions</Link><Link href="/business/login">Connexion professionnelle</Link><Link href="/customer/login">Espace client</Link><Link href="/legal">Mentions légales</Link></div></div></footer>
</div>}
