const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{const db=new PGlite();const q=async(sql,args=[])=> (await db.query(sql,args)).rows;const val=async(sql,args=[])=>Object.values((await q(sql,args))[0])[0];
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth,public to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
 for(const file of ['schema.sql','upgrade-digital-cards-wallet.sql','upgrade-frictionless-client.sql','wallet-personnalisation.sql'])await db.exec(fs.readFileSync(path.join(root,'supabase',file),'utf8').replace(/create extension if not exists pgcrypto;/gi,''));
 await db.exec('grant all on all tables in schema public to service_role;grant select,insert,update,delete on all tables in schema public to authenticated;');
 const install=fs.readFileSync(path.join(root,'supabase/billing-stripe.sql'),'utf8');await db.exec(install);await db.exec(install);
 const owner=await val("insert into auth.users values(gen_random_uuid(),'owner@example.test') returning id");
 await q("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
 await assert.rejects(q("select public.create_business('Café Test','cafe-test','Café offert',5)"),/Abonnement requis/);
 for(const role of ['anon','authenticated']){await db.exec('set role '+role);
  await assert.rejects(q('select * from public.merchant_billing'),/permission denied/);
  await assert.rejects(q("insert into public.merchant_billing(owner_id,status,valid_until) values($1,'active',now()+interval '1 year')",[owner]),/permission denied/);
  await assert.rejects(q('select public.billing_acquire($1)',[owner]),/permission denied/);
  await assert.rejects(q('select public.billing_wallet_access($1)',[owner]),/permission denied/);
  await db.exec('reset role');}
 await db.exec('set role service_role');const lock=await val('select public.billing_acquire($1)',[owner]);assert.ok(lock.lock_token);
 assert.equal(await val('select public.billing_acquire($1)',[owner]),null);
 await q('select public.billing_release($1,gen_random_uuid())',[owner]);assert.equal(await val('select public.billing_acquire($1)',[owner]),null,'wrong lock does not release');
 await q('select public.billing_release($1,$2)',[owner,lock.lock_token]);await db.exec('reset role');
 await q("update public.merchant_billing set plan='wallet',status='trialing',valid_until=now()+interval '15 days',trial_used_at=now(),trial_ends_at=now()+interval '15 days' where owner_id=$1",[owner]);
 const biz=await val("select public.create_business('Café Test','cafe-test','Café offert',5)");
 const prog=await val('select id from public.programs where business_id=$1',[biz]);
 const customer=await val("insert into public.customers(display_name) values('Camille') returning id");
 const member=await val('insert into public.memberships(customer_id,program_id) values($1,$2) returning id',[customer,prog]);
 const visit=await val('select public.record_visit($1)',[member]);assert.ok(visit);
 assert.equal(await val('select public.billing_wallet_access($1)',[member]),true);
 await db.exec('set role service_role');await q('select public.billing_reserve_wallet($1)',[member]);await q('select public.billing_reserve_wallet($1)',[member]);
 assert.equal(Number(await val('select count(*) from public.wallet_allocations')),1);await db.exec('reset role');
 await q("update public.merchant_billing set plan='essentiel' where owner_id=$1",[owner]);
 assert.equal(await val('select public.billing_wallet_access($1)',[member]),false);
 await assert.rejects(q('select public.billing_reserve_wallet($1)',[member]),/Wallet actif/);
 for(const status of ['past_due','unpaid','canceled','paused','incomplete']){
  await q('update public.merchant_billing set status=$2 where owner_id=$1',[owner,status]);
  assert.equal(await val('select public.owns_business($1)',[biz]),false);
  await assert.rejects(q('insert into public.visits(membership_id) values($1)',[member]),/Abonnement requis/);
  await assert.rejects(q("update public.businesses set name='Contournement' where id=$1",[biz]),/Abonnement requis/);
 }
 await q("update public.merchant_billing set status='trialing',valid_until=now()-interval '1 second' where owner_id=$1",[owner]);
 await assert.rejects(q('select public.record_visit($1)',[member]),/Accès refusé/);
 await assert.rejects(q('insert into public.memberships(customer_id,program_id) values($1,$2)',[customer,prog]),/Abonnement requis/);
 await q("update public.merchant_billing set status='active',plan='wallet',valid_until=now()+interval '30 days' where owner_id=$1",[owner]);
 assert.equal(await val('select public.owns_business($1)',[biz]),true);
 await q('insert into public.wallet_allocations(membership_id,business_id) select gen_random_uuid(),$1 from generate_series(1,199)',[biz]);
 const other=await val("insert into public.customers(display_name) values('Léa') returning id");
 const otherMember=await val('insert into public.memberships(customer_id,program_id) values($1,$2) returning id',[other,prog]);
 await assert.rejects(q('select public.billing_reserve_wallet($1)',[otherMember]),/200 cartes/);
 const token=await val('select public_token from public.memberships where id=$1',[member]);
 await q("update public.merchant_billing set status='past_due' where owner_id=$1",[owner]);
 assert.ok(await val('select public.public_card_view($1)',[token]),'customers retain read-only card access');
 await q('delete from public.customers where id=$1',[customer]);assert.equal(Number(await val('select count(*) from public.memberships where id=$1',[member])),0,'privacy deletion remains possible');
 await db.close();console.log('PASS: billing SQL twice, service-only rights, locks, merchant creation gate, expired/failed-payment mutations blocked, Wallet tier and 200 quota, reactivation, customer read/delete preserved');
})().catch(e=>{console.error(e);process.exit(1)});
