const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('typescript');
const root=path.resolve(__dirname,'..');
function load(file,overrides={},globals={}) {
  const exports={};const js=ts.transpileModule(fs.readFileSync(path.join(root,file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  vm.runInNewContext(js,{exports,require:n=>overrides[n]||require(n),process,Buffer,Headers,URL,Response,AbortSignal,...globals},{filename:file}); return exports;
}
const id='11111111-1111-4111-8111-111111111111', token='22222222-2222-4222-8222-222222222222';
const snapshot={membershipId:id,businessId:'business',cardToken:token,active:true,customerName:'Camille Martin',firstName:'Camille',lastName:'Martin',email:'',businessName:'Maison Auguste',joinedAt:'2026-01-01',points:30,rewards:[{name:'Café offert',points_cost:50}]};
const fields=[{key:'prenom',required:true},{key:'commerce',required:true},{key:'points',required:true},{key:'avantage'},{key:'identifiant_carte'}];
const pass={identifier:'provider-id',templateId:'template-id',downloadPage:'https://app.passcreator.com/p/server-generated',appleUrl:'',googleUrl:''};
Object.assign(process.env,{PASSCREATOR_API_KEY:'test-private-key',PASSCREATOR_TEMPLATE_ID:'template-id',NEXT_PUBLIC_SUPABASE_URL:'https://example.supabase.co',NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'public-test',SUPABASE_SERVICE_ROLE_KEY:'server-test',CRON_SECRET:'x'.repeat(40)});
delete process.env.PASSCREATOR_FIELD_MAP;
let queue=[],calls=[];
const fakeFetch=async(url,init)=>{calls.push({url,init,body:init.body?JSON.parse(init.body):null});assert.equal(init.headers.get('Authorization'),'test-private-key');const next=queue.shift();assert.ok(next,'unexpected external API call');if(next.throw)throw Error('secret debug');return new Response(JSON.stringify(next.body),{status:next.status||200});};
const provider=()=>load('lib/passcreator.ts',{}, {fetch:fakeFetch});
const setup=(steps)=>{queue=steps;calls=[];return provider();};
(async()=>{
  let p=provider();assert.equal(p.personalValues(snapshot).points_restants,20);
  assert.match(p.personalValues({...snapshot,points:50}).avantage,/disponible/);
  assert.throws(()=>p.mapTemplateFields([...fields,{key:'unmapped',required:true}],snapshot),/obligatoire/);
  assert.throws(()=>p.mapTemplateFields([{key:'prenom'}],snapshot),/commerce et points/);
  process.env.PASSCREATOR_FIELD_MAP='{"custom":"points"}';assert.equal(p.mapTemplateFields([...fields,{key:'custom'}],snapshot).custom,30);
  process.env.PASSCREATOR_FIELD_MAP='{"barcodeValue":"prenom"}';assert.throws(()=>p.mapTemplateFields(fields,snapshot),/invalide/);delete process.env.PASSCREATOR_FIELD_MAP;
  p=setup([{body:fields},{status:404,body:{}},{body:{success:true,data:{...pass,iPhoneUri:'https://app.passcreator.com/test.pkpass'}}}]);
  const created=await p.syncPass(snapshot);assert.equal(created.identifier,'provider-id');assert.equal(queue.length,0);
  const body=calls.at(-1).body.data;assert.equal(body.prenom,'Camille');assert.equal(body.commerce,'Maison Auguste');assert.equal(body.points,30);assert.equal(body.storedValue,30);assert.equal(body.barcodeValue,'card:'+token);assert.equal(body.userProvidedId,id);assert.equal(body.enforceUniqueUserProvidedId,true);
  assert.equal(calls.at(-1).init.method,'POST');assert.match(calls.at(-1).url,/async=false/);
  p=setup([{body:fields},{body:{success:true}}]);await p.syncPass({...snapshot,points:40},pass);assert.equal(calls.length,2);assert.equal(calls[1].init.method,'PATCH');assert.equal(calls[1].body.data.points,40);assert.equal(calls[1].body.data.templateId,undefined);
  p=setup([{body:fields},{status:404,body:{}},{status:400,body:{}},{body:{identifier:pass.identifier,linkToPassPage:pass.downloadPage}},{body:{success:true}}]);
  assert.equal((await p.syncPass(snapshot)).downloadPage,pass.downloadPage);assert.equal(calls.at(-1).init.method,'PATCH');assert.equal(queue.length,0);
  p=setup([{body:fields},{status:404,body:{}},{body:{success:true,data:{identifier:'test',downloadPage:'javascript:alert(1)'}}}]);await assert.rejects(p.syncPass(snapshot),e=>e.code==='invalid_response');
  p=setup([{status:401,body:{description:'DO NOT LEAK'}}]);await assert.rejects(p.syncPass(snapshot),e=>e.code==='provider_access'&&!e.message.includes('LEAK'));
  p=setup([{throw:true}]);await assert.rejects(p.syncPass(snapshot),e=>e.code==='network'&&!e.message.includes('secret'));
  p=setup([{body:{success:false,statusCode:500}}]);await assert.rejects(p.deletePass(id));
  p=setup([{status:404,body:{}}]);await p.deletePass(id);
  let valid=true,owner=true,publicId=id;
  const client={auth:{getUser:async()=>({data:{user:valid?{id:'user'}:null},error:null})},rpc:async(name,args)=>{assert.equal(name,'public_card_view');assert.equal(args.p_token,token);return {data:publicId?{membership_id:publicId}:null,error:null}},from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{customer:{auth_user_id:owner?'user':'stranger'},program:{business:{owner_id:'merchant'}}},error:null})})};
  const sync=load('lib/wallet-sync.ts',{'@supabase/supabase-js':{createClient:()=>client},'./passcreator':p});
  const req=auth=>({headers:new Headers(auth?{Authorization:'Bearer test'}:{})});
  await assert.rejects(sync.authorizeWallet(req(false),{membershipId:id}),e=>e.status===401);
  await assert.rejects(sync.authorizeWallet(req(true),{membershipId:'bad'}),e=>e.status===400);
  assert.equal(await sync.authorizeWallet(req(true),{membershipId:id,points:999999}),id);
  owner=false;await assert.rejects(sync.authorizeWallet(req(true),{membershipId:id}),e=>e.status===404);owner=true;
  valid=false;await assert.rejects(sync.authorizeWallet(req(true),{membershipId:id}),e=>e.status===401);
  assert.equal(await sync.authorizeWallet(req(false),{accessToken:token,membershipId:'forged',points:999999}),id);
  publicId=null;await assert.rejects(sync.authorizeWallet(req(false),{accessToken:token}),e=>e.status===404);
  let processed=0;
  const worker=load('app/api/wallet/worker/route.ts',{'@/lib/passcreator':{walletServerConfigured:()=>true},'@/lib/wallet-sync':{UUID:sync.UUID,walletAdmin:()=>({}),processWalletJob:async()=>{processed++;return {status:'synced'}}}});
  const hook=(auth,record)=>({headers:new Headers(auth?{Authorization:'Bearer '+process.env.CRON_SECRET}:{}),json:async()=>({table:'wallet_passes',schema:'public',record})});
  assert.equal((await worker.GET(req(false))).status,401);
  assert.equal((await worker.POST(hook(false,{}))).status,401);
  assert.equal((await worker.POST(hook(true,{membership_id:'bad'}))).status,400);
  await worker.POST(hook(true,{membership_id:id,desired_version:2,synced_version:1,lock_token:'locked'}));assert.equal(processed,0);
  await worker.POST(hook(true,{membership_id:id,desired_version:2,synced_version:2}));assert.equal(processed,0);
  await worker.POST(hook(true,{membership_id:id,desired_version:2,synced_version:1}));assert.equal(processed,1);
  console.log('PASS: provider create/PATCH/recovery, field mapping, points, QR identity, safe errors/URLs, customer authorization, protected worker and webhook loop prevention');
})().catch(e=>{console.error(e);process.exit(1)});
